version: '3.8'

services:
  postgres:
    container_name: postgres_container_casadocodigo
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: casadocodigo_boot
    ports:
      - "5432:5432"
    restart: unless-stopped
