# fly.toml app configuration file generated for casa-do-codigo-vini on 2023-11-13T17:06:15-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "casa-do-codigo-vini"
primary_region = "gru"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
